# -*- coding: utf-8 -*-
"""Copy of Data Story-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k824tlTEPRDkucN2jR3MVkmx3WCwq-K-
"""

import pandas as pd
import statistics
import plotly.express as px

from google.colab import files
data_to_upload = files.upload()

df=pd.read_csv(r"savings_data_final.csv")
fig=px.scatter(df,y="quant_saved",color="rem_any")
fig.show()

"""**Yellow Dots** indicate people who *have* been reminded. **Blue Dots** indicate people who *have not* been reminded."""

import csv
import plotly.graph_objects as go
with open('savings_data_final.csv', newline="")as f:
  reader=csv.reader(f)
  saving_data=list(reader)

saving_data.pop(0)
total_entries=len(saving_data)
a=0
for i in saving_data:
    if int(i[3])==1:
      a += 1

fig=go.Figure(go.Bar(x=["reminded","not reminded"],y=[a,total_entries-a]))
fig.show()

"""variable 'a' stands for total number of people who were reminded."""